name: cat_platform

on:
    push:
        branches:
            - '*'
    workflow_dispatch:

env:
    POSTGRES_DB: cat_platform
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_HOST: postgres

jobs:
    deploy:
        if: github.ref_name == 'production'
        runs-on: ubuntu-latest
        steps:
            - name: ssh to pull latest version
              uses: appleboy/ssh-action@master
              with:
                  script: |
                      cd BAD-Project-3
                      ls
                  host: 3.215.58.203 # ip address or your own domain 每次重開server呢到都要改
                  username: ubuntu
                  port: 22
                  key: ${{secrets.CAT_PLATFORM}} #.SSH_PRIVATE_KEY 改咩名都得
